image::https://travis-ci.org/ogama/nebula.svg?branch=master[Build status]

= Nebula

Nebula is a generation tool written in java. Nebula provides simple tools for easy data generation.


The central element in Nebula is the model. The model consists on 

* Entities that describes data structure and the generation behaviours for properties.
* Generation rules that describe how generated data will be format and write

== Getting started

[source,java]
--
package com.nebula.examples.csv;

import com.nebula.core.Model;
import com.nebula.core.ModelBuilder;
import com.nebula.core.Entity;
import com.nebula.core.types.NebulaTypes;
import com.nebula.core.generators.NebulaGenerators;
import com.nebula.core.formatter.NebulaFormatters;
import com.nebula.core.generationconstraint.NebulaConstraints;
import com.nebula.core.generationrule.GenerationRules;
import com.nebula.core.output.NebulaOutputs;

class CsvUsers {

    public static void main(String[] args) {

        System.out.println("Generate 10 Users");

        Model model = ModelBuilder.newEmptyModel()
                .withSeed("a seed")
                .withDateFormat("dd/MM/yyyy")
                .build();

        Entity users = model.newEntity("users", Long.MAX_VALUE);
        users.addProperty("firstName", NebulaGenerators.random(), NebulaTypes.string().withPattern("[A-Z]{1}[a-z]{3,25}"));
        users.addProperty("lastName", NebulaGenerators.random(), NebulaTypes.string().withPattern("[A-Z]{1}[a-z]{3,25}"));
        users.addProperty("dayOfBirth", NebulaGenerators.random(), NebulaTypes.dateTime().range().withMin("01/01/1950").withMax("01/01/2000"));

        model.addGenerationRule(GenerationRules.newOneShootGenerationRule()
                .withEntity(users)
                .withFormatter(NebulaFormatters.csv().withSeparator(";").withColumns("lastName", "firstName", "dayOfBirth"))
                .addOutput(NebulaOutputs.stdout())
                .addGenerationConstraint(NebulaConstraints.amount(10)));

        model.generate();

        System.out.println("Done");
    }
}

--

== Concept

The concept behind Nebula is data generation based on two elements : 

* a seed
* an index

The most important thing is when an entity is declared, Nubula works like an array which all items is a generated object that match entity declaration. All object can be accessible with an index (from 0 to 9223372036854775807). All objects are generated on demand when access via index is perform.

Seed concept is very important. For a same seed nebula will generate the same dataSet.